Add inline cdr doc
nethesis/nethvoice-report pull request #124
Opened 2021-03-17 10:10 UTC by gsanchietti

Add inline doc for CDR.
After the merge, the package should be ready for official release.

2021-03-17 10:11 UTC, gsanchietti commented
Replaces #119

2021-03-17 11:28 UTC, andre8244 requested changes

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_9_pie_inboundAvgDurationByDid.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_8_pie_inboundCallsByDid.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_7_pie_inboundProvinces.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_6_pie_inboundRegions.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_5_bar_inboundMonthlyDistribution.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_7_pie_inboundProvinces.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per visualizzare tutti i dati
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per visualizzare tutti i dati
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_6_pie_inboundRegions.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per visualizzare tutti i dati
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per visualizzare tutti i dati
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_5_bar_inboundMonthlyDistribution.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per visualizzare tutti i dati
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per visualizzare tutti i dati
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_4_bar_inboundHourlyDistribution.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_4_bar_inboundHourlyDistribution.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per visualizzare tutti i dati
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per visualizzare tutti i dati
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_3_pie_inboundAvgWait.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_2_pie_inboundAvgDuration.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_1_pie_inboundCalls.md
> +Numero di chiamate totali *in Entrata* per Fasci selezionati.
```suggestion
Numero di chiamate totali *in Entrata* per i Fasci selezionati.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_1_pie_inboundCalls.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_18_pie_outboundProvinces.md
> +questo numero verranno visualizzate in una sezione `Altri`.
```suggestion
questo numero verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_18_pie_outboundProvinces.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per 
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_17_pie_outboundRegions.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_17_pie_outboundRegions.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per visualizzare tutti i dati
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per visualizzare tutti i dati
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_16_pie_outboundCostByGroup.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_15_pie_outboundCallsByGroup.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_14_pie_outboundCallsByRoute.md
> +Il grafico mostrerà tutti i fasci disponibili.
```suggestion
Il grafico mostra tutti i fasci disponibili.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_14_pie_outboundCallsByRoute.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_12_bar_inboundMonthlyDistributionByDid.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_11_bar_inboundHourlyDistributionByDid.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_12_bar_inboundMonthlyDistributionByDid.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per visualizzare tutti i dati
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per visualizzare tutti i dati
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_11_bar_inboundHourlyDistributionByDid.md
> +Se presente, cliccare il bottone `Visualizza dettagli` per visualizzare tutti i dati
```suggestion
Se presente, cliccare il bottone `Mostra dettagli` per visualizzare tutti i dati
```

2021-03-17 11:28 UTC, andre8244 commented on ui/src/doc-inline/it/cdr/dashboard_default_10_pie_inboundAvgWaitByDid.md
> +verranno visualizzate in una sezione `Altri`.
```suggestion
verranno visualizzati in una sezione `Altri`.
```

2021-03-17 16:54 UTC, andre8244 commented on ui/src/doc-inline/en/cdr/dashboard_default.md
> +This view displays information on the switchboard Inbound calls.
This line refers to "Inbound calls" and is not present in the italian version. Should we remove it?

2021-03-18 10:12 UTC, andre8244 approved these changes
LGTM

2021-03-18 10:14 UTC, merged