Create and populate failed calls table
nethesis/nethvoice-report pull request #21
Opened 2020-10-27 15:01 UTC by Stell0

Failed calls table queue_failed contains call that at the end of the
day have not been answered by operator and whose callers have not been called back

2020-10-27 15:27 UTC, gsanchietti requested changes

2020-10-27 15:27 UTC, gsanchietti commented on root/opt/nethvoice-report/scripts/queue-miner.php
> +
No way :)

Please move table creation to the right place: https://github.com/nethesis/nethvoice-report/blob/master/root/opt/nethvoice-report/scripts/schema.sql

Also *remove* the AUTO_INCREMENT option.

2020-11-02 16:46 UTC, edospadoni approved these changes

2020-11-02 16:51 UTC, gsanchietti approved these changes

2020-11-02 16:57 UTC, merged