Add inline documentation
nethesis/nethvoice-report pull request #90
Opened 2020-12-15 16:29 UTC by andrea-marchionni

Add inline documentation.

2021-01-19 09:56 UTC, gsanchietti requested changes
Partial review.

Things to fix across multiple documents:
- Replace " in table format. " with " in tabular format. "
- use the same from for title and the description
- Remove double back-quotes
- Improve syntax for documents with llists

After these changes, please request the review again

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_3_line_callTotalByHour.md
> +The graph shows the total number of calls received in the working hours for the
```suggestion
The graph shows the total number of calls received during working hours for the 
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_3_line_callTotalByHour.md
> +in table format.
```suggestion
in tabular format.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_4_line_callAnswersByHour.md
> +Hourly distribution of calls *Answered* for selected queues.
```suggestion
Hourly distribution of *Answered* calls for selected queues.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_4_line_callAnswersByHour.md
> +The graph shows the total number of calls answered in the working hours for the
```suggestion
The graph shows the total number of calls answered during working hours for the 
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_4_line_callAnswersByHour.md
> +in table format.
```suggestion
in tabular format.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_5_line_callLostByHour.md
> +The graph shows the total number of unanswered calls in the working hours for the
```suggestion
The graph shows the total number of unanswered calls during working hours for the 
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_5_line_callLostByHour.md
> +in table format.
```suggestion
in tabular format.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/dashboard_default_10_line_totalCalls.md
> +centralino in tempo reale al variare del tempo.
Please avoid repetition

```suggestion
centralino in tempo reale al variare del tempo.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/dashboard_default_2_pie_callByAgentTotal.md
> +Numero di chiamate *Risposte* da ogni agente selezionato delle code selezionate.
Please avoid repetition.

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/dashboard_default_2_pie_callByAgentTotal.md
> +lo mette a confronto proporzionale con gli altri agenti selezionati, i dati si riferiscono
"confronto proporzionale" doesn't sound well

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/dashboard_default_6_bar_callDoneByAgentByHour.md
> +Se nessuna agente è stato selezionato, il grafico non verrà mostrato.
```suggestion
Se nessun agente è stato selezionato, il grafico non verrà mostrato.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/dashboard_default_7_line_IVRChoicesByHour.md
> +Distribuzione oraria delle *Scelte* effettuate negli IVR(Interactive Voice Response) selezionati
```suggestion
Distribuzione oraria delle *Scelte* effettuate negli IVR (Interactive Voice Response) selezionati
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/dashboard_default_8_pie_uniqCid.md
> +code selezionatee lo mette a confronto in modo proporzionale.
```suggestion
code selezionate e lo mette a confronto in modo proporzionale.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/dashboard_default_8_pie_uniqCid.md
> +coda contati singolarmente.
```suggestion
coda, contati singolarmente.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/data_agent_1_table_agent.md
> +Dati suddivisi *per Agente* selezionato nelle code selezionate nel
Avoid repetition

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/data_agent_1_table_agent.md
> +telefonate con cui hanno interagito per ogni agente selezionato.
This is not very clear.

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/data_agent_1_table_agent.md
> +- Dopo Chiusura (il totale del tempo che ogni coda può concedere
This section should use a better formatting.
Something like:
```
- `Periodo di Raggruppamento`
...
- `Dopo Chiusura`: il totale del tempo che ogni coda può concedere 
```

Or, as alternative:
```
- `Periodo di Raggruppamento`
...
- *Dopo Chiusura*: il totale del tempo che ogni coda può concedere 
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/it/data_agent_1_table_agent.md
> +agenti di tutte le code disponibili.
```suggestion
Se nessun agente è stato selezionato, verranno mostrati i dati di tutti 
gli agenti. Se nessuna coda è stata selezionata, verranno mostrati gli 
agenti di tutte le code disponibili.
```

2021-01-19 09:56 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_11_line_callsOnQueue.md
> +will appear in ``Others`` section.
Correct markdown syntax:
```suggestion
will appear in `Others` section.
```

2021-01-19 10:17 UTC, edospadoni commented on ui/src/doc-inline/en/dashboard_default_10_line_totalCalls.md
> +Number of *Total* callc of all switchboard queues.
```suggestion
Number of *Total* calls of all switchboard queues.
```

2021-01-20 09:59 UTC, andre8244 requested changes
In addition to the typos reported, I would use a smaller header (`###`) for every documentation title (e.g. `# Total Calls` -> `### Total Calls`).

I think the header currently used (`#`) looks too big (see picture below).

I can do it as a final commit before merging.

![image](https://user-images.githubusercontent.com/4612169/105158488-4e85e680-5b0e-11eb-9edb-99d536bc656d.png)

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/performance_default_3_table_talkTime.md
> +chiamate divisi in fasce di tempo pre determinate.
```suggestion
chiamate divisi in fasce di tempo predeterminate.
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/performance_default_2_table_qos.md
> +I dati del *Qualità del Servizio (QoS)* mostrano i tempi di risposta
```suggestion
I dati della *Qualità del Servizio (QoS)* mostrano i tempi di risposta 
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/performance_default_2_table_qos.md
> +Le voci mostrate per le *Qualità del Servizio (QoS)* sono:
```suggestion
Le voci mostrate per la *Qualità del Servizio (QoS)* sono: 
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/performance_default_1_table_performance.md
> +del funzionamento delle code ed a evidenziarne le criticità.
```suggestion
del funzionamento delle code e ad evidenziarne le criticità.
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/performance_default_1_table_performance.md
> +chiamante dopo dell'attesa minima impostata
```suggestion
chiamante dopo l'attesa minima impostata
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/graphs_hour_11_line_ivr.md
> +Se nessuna IVR è stato selezionato, non verranno mostrati i dati.
```suggestion
Se nessun IVR è stato selezionato, non verranno mostrati i dati.
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/graphs_hour_11_line_ivr.md
> +numero verranno visualizzate in una sezione `Altri`.
```suggestion
numero verranno visualizzati in una sezione `Altri`.
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/graphs_hour_10_line_callDoneByAgent.md
> +Se nessuna agente è stato selezionato, non verranno mostrati i dati.
```suggestion
Se nessun agente è stato selezionato, non verranno mostrati i dati.
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/graphs_avg_duration_1_line_queueDuration.md
> +*Durata della Chiamata* per le code selezionate nell'orario lavorativo impostato.
```suggestion
```
This line is probably not needed, next sentence says the same concepts and adds more details

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/graphs_agent_4_line_agentsOnQueue.md
> +Numero di *Agenti* in loggati in coda per le code selezionate.
```suggestion
Numero di *Agenti* loggati in coda per le code selezionate.
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/graphs_agent_4_line_agentsOnQueue.md
> +visualizzando momenti quando il totale degli agenti ha avuto una variazione in
```suggestion
visualizzando i momenti in cui il totale degli agenti ha avuto una variazione in 
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/graphs_agent_3_pie_agentsCallsDone.md
> +Se nessuna agente è stato selezionato, il grafico non mostrerà dati.
```suggestion
Se nessun agente è stato selezionato, il grafico non mostrerà dati.
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/data_ivr_1_table_ivr.md
> +numeriche previste sono possibili la scelta i che indica chi ha fatto
```suggestion
numeriche previste sono possibili la scelta `i` che indica chi ha fatto 
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/data_ivr_1_table_ivr.md
> +una scelta invalida, cioè non prevista dall'IVR, e la scelta t che
```suggestion
una scelta invalida, cioè non prevista dall'IVR, e la scelta `t` che 
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/distribution_hourly_11_table_ivr.md
> +numeriche previste sono possibili la scelta i che indica chi ha fatto
```suggestion
numeriche previste sono possibili la scelta `i` che indica chi ha fatto
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/distribution_hourly_11_table_ivr.md
> +una scelta invalida, cioè non prevista dall'IVR, e la scelta t che
```suggestion
una scelta invalida, cioè non prevista dall'IVR, e la scelta `t` che
```

2021-01-20 09:59 UTC, andre8244 commented on ui/src/doc-inline/it/dashboard_default_2_pie_callByAgentTotal.md
> +Se nessuna agente è stato selezionato, il grafico mostrerà tutti gli agenti disponibili.
```suggestion
Se nessun agente è stato selezionato, il grafico mostrerà tutti gli agenti disponibili.
```

2021-01-20 10:28 UTC, gsanchietti requested changes
Items marked with `?` contains common errors (eg. "queue selected" vs "selected queues").

Items marked with `??` has no meaning and should be completely rewritten.

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/graphs_area_1_pie_prefix.md
> +for the queues select and compare the data proportionally.
```suggestion
The pie chart shows the total incoming calls grouped by caller *Prefix*.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/graphs_area_1_pie_province.md
> +for the queues select and compare the data proportionally.
```suggestion
The pie chart shows the total incoming calls grouped by caller *Province*.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/graphs_area_1_pie_region.md
> +for the queues select and compare the data proportionally.
```suggestion
The pie chart shows the total incoming calls grouped by caller *Regione*.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_caller_1_table_caller.md
> +the choice made in the filters.
```suggestion
Data broken down *by Caller* of calls entered selected queues in a specific time range grouped according to the chosen filter criteria.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_caller_1_table_caller.md
> +callers from all available queues.
```suggestion
If no caller has been selected, all caller will be shown.
If no queue has been selected, all queues will be shown.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_lost_call_1_table_lostCall.md
> +made in the filters.
```suggestion
Data split *by Unhandled Calls* in selected queues
during the configured perido. Dare are grouped according to the chosen filter criteria.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_lost_call_1_table_lostCall.md
> +by an agent.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_session_1_table_session.md
> +the choice made in the filters.
```suggestion
Data broken down *by Session* of the agents selected in the queues
during configured period. Data are grouped according to chosen filter criteria.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_session_1_table_session.md
> +agents of all available queues
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_1_table_good.md
> +in the filters.
```suggestion
*Answered* calls for selected queues in the given period. Dara are grouped according to the chosen filter criteria.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_1_table_good.md
> +the queues available.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_2_table_failed.md
> +in the filters.
```suggestion
*Failed* calls data for selected queue in a specific time range.
Data are grouped according to the chosen filter criteria.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_2_table_failed.md
> +caller.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_2_table_failed.md
> +the queues available.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_3_table_timeout.md
> +in the queue.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_4_table_exitempty.md
> +according to the choice made in the filters.
"selected queues" not "queues selected"

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_4_table_exitempty.md
> +queue) and consequently were dropped from the queue.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_4_table_exitempty.md
> +the queues available.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_5_table_exitkey.md
> +in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_6_table_full.md
> +in the filters.
```suggestion
Data regarding failed calls for *Full Queue* for the selected queues
during the given period.
Data are grouped according to the chosen filter criteria.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_6_table_full.md
> +automatically.
"achieved" is wrong in this context, it should be "reached"

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_6_table_full.md
> +the queues available.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_7_table_joinempty.md
> +choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_8_table_null.md
> +made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_8_table_null.md
> +the queues available.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_9_table_callDoneByAgent.md
> +the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_9_table_callDoneByAgent.md
> +completed by each selected agent.
"completed calls"

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/data_summary_9_table_callDoneByAgent.md
> +agents available.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_geographic_1_table_geographic.md
> +according to the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_10_table_callDoneByAgent.md
> +they are grouped according to the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_10_table_callDoneByAgent.md
> +set to.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_1_table_total.md
> +the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_1_table_total.md
> +calls during the set working hours.
"arrival"? maybe "received" ...

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_2_table_good.md
> +the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_2_table_good.md
> +calls answered within the set working hours.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_4_table_timeout.md
> +grouped according to the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_4_table_timeout.md
> +configured in the set working hours.
```suggestion
of unanswered calls within the configured maximum waiting time.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_3_table_failed.md
> +grouped according to the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_3_table_failed.md
> +set in the working hours set.
??

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_5_table_exitempty.md
> +grouped according to the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_6_table_exitkey.md
> +grouped according to the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_6_table_exitkey.md
> +to exit the queue during the set working hours.
```suggestion
The *Time Distribution Exit Menu Calls* shows the division
of calls in which the caller used the Exit Menu 
to exit the queue.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_7_table_full.md
> +according to the choice made in the filters.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/distribution_hourly_7_table_full.md
> +waiting in queue reached within the set working hours.
?

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/performance_default_1_table_performance.md
> +operation and evaluate its *Performance* over time.
```suggestion
Data regarding the selected queues useful to summarize the
workload and evaluate pbx *Performance* over time.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/performance_default_1_table_performance.md
> +the functioning of the queues and to highlight the critical issues.
```suggestion
The *Performance* data of the queues are used to evaluate current workload and highlight critical issues.
```

2021-01-20 10:28 UTC, gsanchietti commented on ui/src/doc-inline/en/performance_default_1_table_performance.md
> +the queues available.
?

2021-01-20 13:09 UTC, gsanchietti commented
> In addition to the typos reported, I would use a smaller header (`###`) for every documentation title (e.g. `# Total Calls` -> `### Total Calls`).

I think that using the main header (`#`) is the right choice for the documents: it prevents confusion.
But I agree that the title is a little too big: can we eventually make it a little smaller using css?

2021-01-21 08:58 UTC, andre8244 commented
> > In addition to the typos reported, I would use a smaller header (`###`) for every documentation title (e.g. `# Total Calls` -> `### Total Calls`).
> 
> I think that using the main header (`#`) is the right choice for the documents: it prevents confusion.
> But I agree that the title is a little too big: can we eventually make it a little smaller using css?

Good idea :+1: https://github.com/nethesis/nethvoice-report/pull/104

2021-01-21 09:21 UTC, gsanchietti requested changes
After a quick search, I can see at least 10 errors where the  `queues selected` form is still used. :(

2021-01-21 09:21 UTC, gsanchietti commented on ui/src/doc-inline/en/data_call_1_table_call.md
> +*Calls* entered the queues selected in
```suggestion
*Calls* entered the selected queues in
```

2021-01-21 10:18 UTC, gsanchietti requested changes

2021-01-21 10:18 UTC, gsanchietti commented on ui/src/doc-inline/en/dashboard_default_8_pie_uniqCid.md
> +the queues available.
```suggestion
If no queues have been selected, the graph will show the unique callers of all
the available queues.
```

2021-01-21 10:19 UTC, gsanchietti approved these changes

2021-01-21 11:01 UTC, merged